{
 "title": "PostgreSQL (postgres_exporter)",
 "description": "postgres exporter Dashboard for display important postgreSQL metric",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "label_values({job=\"postgres-exporter\"}, instance)"
   },
   { "name": "Database", "query": "label_values(datname)" },
   { "name": "Interval", "query": "30sec,1m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  { "title": "전체 통계", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PostgreSQL 버전",
   "type": "singlestat",
   "description": "Source: server_version_num",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(pg_settings_server_version_num)"
    }
   ]
  },
  {
   "title": "최대 복제 지연",
   "type": "singlestat",
   "description": "Max Replication lag behind master in seconds\n\nOnly available on a standby system.\n\nSource: pg_last_xact_replay_timestamp\n\nUse: pg_stat_replication for Details.",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "s",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(pg_replication_lag_seconds{instance=\"$Instance\"})"
    }
   ]
  },
  {
   "title": "실행 중인 클라이언트",
   "type": "singlestat",
   "description": "Clients executing Statements.\n\nSource: pg_stat_activity",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"active\",instance=\"$Instance\"})"
    }
   ]
  },
  {
   "title": "공유 버퍼 적중률",
   "type": "gauge",
   "description": "Shared buffer hits vs reads from disc",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{instance=~\"$Instance\"})/(sum(pg_stat_database_blks_hit{instance=~\"$Instance\"})+sum(pg_stat_database_blks_read{instance=~\"$Instance\"}))*100"
    }
   ]
  },
  {
   "title": "커넥션 사용률",
   "type": "gauge",
   "description": "Percentage of max_connections used",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_numbackends)/max(pg_settings_max_connections)"
    }
   ]
  },
  {
   "title": "커밋 비율",
   "type": "gauge",
   "description": "Transaction committed vs rollbacked",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_xact_commit{instance=\"$Instance\"})/(sum(pg_stat_database_xact_commit{instance=\"$Instance\"}) + sum(pg_stat_database_xact_rollback{instance=\"$Instance\"}))"
    }
   ]
  },
  {
   "title": "PostgreSQL 가동 시간",
   "type": "singlestat",
   "description": "Source: pg_postmaster_start_time()\n\n지금은 빈다. pg_postmaster_start_time_seconds를 내는 postmaster 컬렉터가 기본 비활성이다(활성 15개 목록에 없음). postgres_exporter에 플래그를 줘야 채워진다.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time()-(pg_postmaster_start_time_seconds{instance=\"$Instance\"})"
    }
   ]
  },
  {
   "title": "초당 트랜잭션",
   "type": "singlestat",
   "description": "Transactions committed + roolback per minute\n\nSource: pg_stat_database,xact_commit + xact_rollback",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_xact_commit{instance=\"$Instance\"}[$Interval])))+sum((rate(pg_stat_database_xact_rollback{instance=\"$Instance\"}[$Interval])))"
    }
   ]
  },
  {
   "title": "초당 쿼리",
   "type": "singlestat",
   "description": "Statements executed per Minute.\n\nSource: pg_stat_statements.calls\n\n지금은 빈다. pg_stat_statements 확장이 설치돼 있지 않다. shared_preload_libraries 수정과 PostgreSQL 재시작이 필요하다.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum((rate(pg_stat_statements_calls{instance=\"$Instance\"}[$Interval])))"
    }
   ]
  },
  {
   "title": "전체 DB 용량",
   "type": "singlestat",
   "description": "Size of all databases in $Instance.\n\nSource: pg_database_size_bytes()",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pg_database_size_bytes{instance=\"$Instance\"})"
    }
   ]
  },
  {
   "title": "평균 쿼리 실행 시간",
   "type": "singlestat",
   "description": "Source: pg_stat_statements.total_time / pg_stat_statements.calls\n\n지금은 빈다. pg_stat_statements 확장이 설치돼 있지 않다. shared_preload_libraries 수정과 PostgreSQL 재시작이 필요하다.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum((delta(pg_stat_statements_total_time_seconds{instance=\"$Instance\"}[$Interval])))/sum((delta(pg_stat_statements_calls{instance=\"$Instance\"}[$Interval])))"
    }
   ]
  },
  {
   "title": "공유 버퍼 크기",
   "type": "singlestat",
   "description": "Setting: shared_buffers in PostgreSQL.conf",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "최대 커넥션 수",
   "type": "singlestat",
   "description": "Setting: max_connections in postgreSQL.conf",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_max_connections{instance=\"$Instance\"}"
    }
   ]
  },
  {
   "title": "상태별 커넥션",
   "type": "graph",
   "description": "View: pg_stat_activity",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (pg_stat_activity_count{instance=\"$Instance\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "DB별 커넥션",
   "type": "graph",
   "description": "View: pg_stat_activity",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) (pg_stat_activity_count{instance=\"$Instance\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "트랜잭션 (커밋 · 롤백)",
   "type": "graph",
   "description": "1 Minute rate of transactions committed or rollback.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum ((rate(pg_stat_database_xact_commit[$Interval])))",
     "legendFormat": "committed"
    },
    {
     "expr": "sum ((rate(pg_stat_database_xact_rollback[$Interval])))",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "튜플 삽입 · 수정 · 삭제",
   "type": "graph",
   "description": "Source: pg_stat_database",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_tup_inserted{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum((rate(pg_stat_database_tup_updated{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum((rate(pg_stat_database_tup_deleted{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "디스크 읽기 · 쓰기 시간",
   "type": "graph",
   "description": "* blk_read_time: Time spent reading data file blocks by backends in this database, in milliseconds\n* blk_write_time: Time spent writing data file blocks by backends in this database, in milliseconds\n\ntrack_io_timings needs to be activated",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum ((rate(pg_stat_database_blk_read_time{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "blk_read_time"
    },
    {
     "expr": "sum ((rate(pg_stat_database_blk_write_time{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "blk_read_time"
    }
   ]
  },
  {
   "title": "튜플 조회 · 반환",
   "type": "graph",
   "description": "Source: pg_stat_database\n\n* tup_fetched: rows needed to satisfy queries\n* tup_returned: rows read/scanned",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum((rate(pg_stat_database_tup_fetched{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum((rate(pg_stat_database_tup_returned{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "Returned"
    }
   ]
  },
  {
   "title": "상태별 락",
   "type": "graph",
   "description": "Source: pg_locks",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (pg_locks_count{instance=\"$Instance\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "DB별 데드락",
   "type": "graph",
   "description": "Should be 0 \n\nSource: pg_stat_database\n\nWith log_lock_waits turned on, deadlocks will be logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) ((rate(pg_stat_database_deadlocks{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "DB별 임시 파일",
   "type": "graph",
   "description": "Should be 0. If temporary files are created, it can indicate insufficient work_mem. With log_temp_files the creation of temporary files are logged to the PostgreSQL Logfiles.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (datname) ((rate(pg_stat_database_temp_files{instance=\"$Instance\"}[$Interval])))",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "복제 지연",
   "type": "graph",
   "description": "Lag behind master in seconds.\n\nOnly available on a standby System.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(pg_replication_lag_seconds{instance=\"$Instance\"})",
     "legendFormat": "lag "
    }
   ]
  },
  {
   "title": "데이터베이스: $Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "repeat": "Database",
   "collapsed": true,
   "panels": [
    {
     "title": "실행 중인 클라이언트",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_stat_activity_count{state=\"active\",instance=\"$Instance\",datname=~\"$Database\"}"
      }
     ]
    },
    {
     "title": "DB 용량",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_database_size_bytes{instance=\"$Instance\",datname=\"$Database\"}"
      }
     ]
    },
    {
     "title": "공유 버퍼 적중률",
     "type": "gauge",
     "description": "Shared buffer hits vs reads from disc",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_stat_database_blks_hit{instance=~\"$Instance\",datname=~\"$Database\"}/(pg_stat_database_blks_hit{instance=~\"$Instance\",datname=~\"$Database\"}+pg_stat_database_blks_read{instance=~\"$Instance\",datname=~\"$Database\"})"
      }
     ]
    },
    {
     "title": "커밋 비율",
     "type": "gauge",
     "description": "Transaction committed vs rollbacked",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pg_stat_database_xact_commit{instance=\"$Instance\",datname=~\"$Database\"}/(pg_stat_database_xact_commit{instance=\"$Instance\",datname=~\"$Database\"} + pg_stat_database_xact_rollback{instance=\"$Instance\",datname=~\"$Database\"})"
      }
     ]
    },
    {
     "title": "초당 트랜잭션",
     "type": "singlestat",
     "description": "Transactions committed + roolback per minute\n\nSource: pg_stat_database,xact_commit + xact_rollback",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum((rate(pg_stat_database_xact_commit{instance=\"$Instance\",datname=\"$Database\"}[$Interval])))+sum((rate(pg_stat_database_xact_rollback{instance=\"$Instance\",datname=\"$Database\"}[$Interval])))"
      }
     ]
    },
    {
     "title": "상태별 커넥션",
     "type": "graph",
     "description": "View: pg_stat_activity",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (state) (pg_stat_activity_count{instance=\"$Instance\",datname=\"$Database\"})",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "트랜잭션 (커밋 · 롤백)",
     "type": "graph",
     "description": "1 Minute rate of transactions committed or rollback.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_database_xact_commit{instance=\"$Instance\",datname=\"$Database\"}[$Interval])",
       "legendFormat": "committed"
      },
      {
       "expr": "rate(pg_stat_database_xact_rollback{instance=\"$Instance\",datname=\"$Database\"}[$Interval])",
       "legendFormat": "rollback"
      }
     ]
    },
    {
     "title": "튜플 삽입 · 수정 · 삭제",
     "type": "graph",
     "description": "Source: pg_stat_database",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_inserted{instance=\"$Instance\",datname=\"$Database\"}[$Interval])",
       "legendFormat": "Inserts"
      },
      {
       "expr": "rate(pg_stat_database_tup_updated{instance=\"$Instance\",datname=\"$Database\"}[$Interval])",
       "legendFormat": "Updates"
      },
      {
       "expr": "rate(pg_stat_database_tup_deleted{instance=\"$Instance\",datname=\"$Database\"}[$Interval])",
       "legendFormat": "Deletes"
      }
     ]
    },
    {
     "title": "튜플 조회 · 반환",
     "type": "graph",
     "description": "Source: pg_stat_database\n\n* tup_fetched: rows needed to satisfy queries\n* tup_returned: rows read/scanned",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_database_tup_fetched{instance=\"$Instance\",datname=\"$Database\"}[$Interval])",
       "legendFormat": "Fetched"
      },
      {
       "expr": "rate(pg_stat_database_tup_returned{instance=\"$Instance\",datname=\"$Database\"}[$Interval])",
       "legendFormat": "Returned"
      }
     ]
    },
    {
     "title": "상태별 락",
     "type": "graph",
     "description": "Source: pg_locks",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum by (mode) (pg_locks_count{instance=\"$Instance\",datname=\"$Database\"})",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "DB별 데드락",
     "type": "graph",
     "description": "Should be 0 \n\nSource: pg_stat_database\n\nWith log_lock_waits turned on, deadlocks will be logged to the PostgreSQL Logfiles.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_database_deadlocks{instance=\"$Instance\",datname=\"$Database\"}[$Interval])",
       "legendFormat": "deadlocks"
      }
     ]
    },
    {
     "title": "DB별 임시 파일",
     "type": "graph",
     "description": "Should be 0. If temporary files are created, it can indicate insufficient work_mem. With log_temp_files the creation of temporary files are logged to the PostgreSQL Logfiles.",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(pg_stat_database_temp_files{instance=\"$Instance\",datname=\"$Database\"}[$Interval])",
       "legendFormat": "temp_files"
      }
     ]
    }
   ]
  }
 ]
}